Features/task 3
LindaLangerova/kentico-onboarding-cs pull request #5
Opened 2018-03-26 19:47 UTC by LindaLangerova

2018-05-15 09:04 UTC, vaclavm requested changes
Hi! It is nice and clear what you get there. Let's make your code a little bit more complex 👼.

First of all, consider adding the new project for services. Maybe you are asking why, as you have only UrlGenerator service ... well, you should add some new services. How exciting! 
1) Think about caching service that will test the existence of Item in the databases (saves it in property = cache) and then return the item to your controller. You will try this way how caching works and moreover, you will get rid of validating null when getting item (more in my comments below).
2) Let's make the saving item to the DB is a little bit more complex. You should have a service that will create the whole Item before saving it to the database. You know, to save dates in the item, to create proper Id (yes, you should be in control).
3) ... and some more, as you can read in my comments

Want a challenge? Separate Unity framework from your project! Make a proxy project, that will work with Unity but all your other projects would be separated from Unity and will work with the proxy project. In this way, you can change DI provider from Unity to any other and your code would not suffer. Think about it ;-),

If you need any more assistance, just ask me and I will gladly describe everything I have written in the comments. It is possible I have missed something so you can look forward to the second review!

2018-05-15 09:04 UTC, vaclavm commented on TodoApp/src/TodoApp.Api/Controllers/ItemListController.cs
> +            if (result == null) return NotFound();
You can get rid of this check and return just OK result.
Null suggests there is a missing resource, it GetAllAsync case the resource is the whole collection.

2018-05-15 09:04 UTC, vaclavm commented on TodoApp/src/TodoApp.Api/Controllers/ItemListController.cs
> +            return await Task.FromResult(Created(location, newItemText));
You should return whole new Item (as you do in Get). The controller is for ItemList so the return types should be alike in the whole controller. Moreover ... How would the client get the item details, if there will be any?

2018-05-15 09:04 UTC, vaclavm commented on TodoApp/src/TodoApp.Api/Controllers/ItemListController.cs
> +            if (item.Text == null)
You are accepting whole Item model but checking only for Text. What if the client sents item with CreatedAt changed? What if the item has Id set from the client?
The client can send you anything and it is server job to correctly check for the valid state of the model. It our application the client is responsible only for Text handling, therefore you should validate the argument as a whole and return BadRequest if anything except Text is set. I strongly recommend using your own validation service as you will also need the validation in Put :).
PS: If you don't want to restrict the client so much (client knows that the model consists of multiple properties) you can create ViewModel for the API that will be accepted by POST/PUT - more info personally.

2018-05-15 09:04 UTC, vaclavm commented on TodoApp/src/TodoApp.Api/Controllers/ItemListController.cs
> +            if (item == null)
It is not best practice to check for null in the controllers - for example, the repository could return an empty object instead of null and the check would be useless.
It is better to check if the item is in the database and then get it (simple cached service).

2018-05-15 09:04 UTC, vaclavm commented on TodoApp/src/TodoApp.Api/Controllers/ItemListController.cs
> +            var newItemText = await _repository.Add(item);
I am missing some save/modify service that will set all other properties (CreatedAt, LastChange) before saving the item in the DB.

2018-05-15 09:04 UTC, vaclavm commented on TodoApp/src/TodoApp.Data/Repositories/ItemRepository.cs
> +    public class ItemRepository : IItemRepository
Add Async as suffices to all methods name.

2018-05-15 09:04 UTC, vaclavm commented on TodoApp/src/TodoApp.Data/Repositories/ItemRepository.cs
> +            var database = client.GetDatabase("tododb");
`var databaseUrl = MongoUrl.Create(connectionString);`
`var database = new MongoClient(databaseUrl).GetDatabase(databaseUrl.DatabaseName);`
=> getting rid of "tododb"

2018-05-15 09:04 UTC, vaclavm commented on TodoApp/src/TodoApp.Data/Repositories/ItemRepository.cs
> +        public async Task<string> Add(Item item)
The method should return Item :)

2018-05-15 09:04 UTC, vaclavm commented on TodoApp/src/TodoApp.Contract/Contexts/IItemDbContext.cs
> +    public interface IItemDbContext : IDisposable
You can delete this file. You don't use it anymore.

2018-05-15 09:04 UTC, vaclavm commented on TodoApp/src/TodoApp.Api/TodoApp.Api.csproj
>      <Folder Include="App_Data\" />
Whole folder can be deleted from the solution.

2018-05-15 09:04 UTC, vaclavm commented on TodoApp/src/TodoApp.Data/Repositories/ItemRepository.cs
> +        public ItemRepository(string connectionString)
Instead of passing connection string as a string, try to create an interface that will provide to connection string on request ;-).

2018-05-15 09:04 UTC, vaclavm commented on TodoApp/src/TodoApp.Data/DataUnityBootstrapper.cs
> +                                                                      new InjectionConstructor(ConfigurationManager.ConnectionStrings["DefaultConnection"].ConnectionString));
`ConfigurationManager.ConnectionStrings["DefaultConnection"].ConnectionString`
Getting the connection string should not be the responsibility of TodoApp.Data as this project could work as a library. The connection string should be passed by project using the TodoApp.Data.
To correctly pass the connection string to the repository, look at ItemRepository.cs commentary.

2018-05-15 09:04 UTC, vaclavm commented on TodoApp/src/TodoApp.Api/Controllers/ItemListController.cs
> +            var newItemText = await _repository.Add(item);
Also in that service you should be responsible for Id creation. Right now the Id of the item is created by repository, you are not in control. There are some real-life examples that shows it is better to be in control when creating Id (just ask me or Petr).

2018-05-15 09:04 UTC, vaclavm commented on TodoApp/test/TodoApp.Api.Tests/Controllers/ItemListController.test.cs
> +    public class ItemListControllerTest : TestBase
You are not testing all code paths: Get (NotFound), Post (BadRequest).

2018-05-15 09:04 UTC, vaclavm commented on TodoApp/test/TodoApp.Api.Tests/Controllers/ItemListController.test.cs
> +            var fakeItem = new Item {Id = fakeId, Text = "Make a coffee"};
This can be made a property of the whole test because it is used multiple times. ("constant phenomenon 😆" as would Petr said)

2018-05-15 09:04 UTC, vaclavm commented on TodoApp/test/TodoApp.Api.Tests/Controllers/ItemListController.test.cs
> +                          .Returns(new[]
Again "constant phenomenon 😆"

2018-05-15 09:04 UTC, vaclavm commented on TodoApp/test/TodoApp.Api.Tests/Controllers/ItemListController.test.cs
> +            urlGenerator.GetItemUrl(Arg.Any<Guid>()).Returns("api/v1/itemlist/c5cc89a0-ab8d-4328-9000-3da679ec02d3");
Make "c5cc89a0-ab8d-4328-9000-3da679ec02d3" a constant and use:
`$"api/v1/itemlist/{idConstant}"`

2018-05-15 09:04 UTC, vaclavm commented on TodoApp/test/TodoApp.Api.Tests/Services/UrlGenerator.test.cs
> +        private UrlGenerator _itemUrlGenerator;
Move it above SetUp :)

2018-05-15 09:04 UTC, vaclavm commented on TodoApp/test/TodoApp.Api.Tests/Controllers/ItemListController.test.cs
> +        public async Task DeleteItem_ItemDeleted()
Move it below Put - corresponding location in Controller.

2018-05-15 09:04 UTC, vaclavm commented on TodoApp/src/TodoApp.Contract/Models/Item.cs
> +            => $"{nameof(Id)}: {Id}, {nameof(Text)}: {Text}";
This should reflect all properties :)

2018-06-01 09:18 UTC, vaclavm reviewed
The solution is getting a real-life structure! Very well, young padawan!

Now let's have a look at the new project you have created for the services:
* Please rename it as there is a typo: Todo.App.Services instead of correct TodoApp.Services
* All your folders are named with the save postfix (Services), don't be shy and create all kind of different folders corresponding with the types (UrlGenerator and IdGenerator could be in folder Generators, ItemCacher is a provide - feel free to rename it and create a folder for Providers, ... and in the end it looks like you don't need any Services folder)
* By having interfaces for the services in the TodoApp.Services project, you are kind of breaking references in the solution as the services shouldn't be public. They should be visible only to the TodoApp.Services project (and tests). It would be much better to move the interfaces to Contract project as this project is the reference point for the whole application. You describe interfaces in there, reference them in the Api project and you should inject services for the interfaces in the Services project (create ServicesBootstrapper as an entry point for the project). Therefore the implementation of these interfaces would be hidden for the rest of the application.

2018-06-01 09:18 UTC, vaclavm commented on TodoApp/src/TodoApp.Api/Controllers/ItemsController.cs
> +            if (await _itemCacher.ItemExists(item.Id))
As item.Id should be unique, this check is redundant for our purposes

2018-06-01 09:18 UTC, vaclavm commented on TodoApp/src/TodoApp.Api/Controllers/ItemsController.cs
> +                return BadRequest();
The check for validity is correct, but you should check it before creating/setting item - see comment in SetItem further in this review.

2018-06-01 09:18 UTC, vaclavm commented on TodoApp/Todo.App.Services/ItemServices/ItemCacher.cs
> +            try
Do you really need this try-catch block? IMongoCollection.Find().FirstOrDefaultAsync() should return the item from the collection or null so why catching NullReferenceException?
If there is some a problem in the _repository (IMongoCollection doesn't exist for example) then the exception should be thrown to point out the problem. By catching it, you ignore the real problem and you only return that the item doesn't exist.

2018-06-01 09:18 UTC, vaclavm commented on TodoApp/Todo.App.Services/ItemServices/ItemCacher.cs
> +            if (_actualItem != null && _actualItem.Id == id)
This can be simplified to _actualItem?.Id and if you change the if statement, you can have only one return in whole method ;-)

2018-06-01 09:18 UTC, vaclavm commented on TodoApp/Todo.App.Services/ItemServices/ItemCreator.cs
> +            if (!item.IsValidForCreating())
By this check, you are breaking Single Responsibility Principle :). SetItem is only responsible for setting the item. The check for validity should be moved upper the code chain -> in the controller.

2018-06-01 09:18 UTC, vaclavm commented on TodoApp/Todo.App.Services/ItemServices/ItemCreator.cs
> +            item.Text = item.Text;
Redundant :)

2018-06-01 09:18 UTC, vaclavm commented on TodoApp/Todo.App.Services/ItemServices/ItemValidator.cs
> +    public static class ItemValidator
Nice extension!

2018-06-01 09:18 UTC, vaclavm commented on TodoApp/src/TodoApp.Api/ApiUnityBootstrapper.cs
> +            => container.RegisterType<IUrlGenerator, UrlGenerator>(new HierarchicalLifetimeManager())
Registration for services should be in Services project (just like you have it for Data ;-) )

2018-06-01 09:18 UTC, vaclavm commented on TodoApp/src/TodoApp.Data/DataUnityBootstrapper.cs
> +                        .RegisterType<IConnectionStringProvider, ConnectionStringProvider>(new ContainerControlledLifetimeManager());
This registering should be in Todo.App.Services UnityBootstraper Register method.
I know that connection string is related to the repository but every project should register only its own services.

2018-06-01 09:18 UTC, vaclavm commented on TodoApp/src/TodoApp.Data/Repositories/ItemRepository.cs
> +
You don't have to return the item as it is a reference type, the item.Id is correctly changed.

2018-06-01 09:18 UTC, vaclavm commented on TodoApp/src/TodoApp.Api/App_Start/RouteConfig.cs
> +            config.EnableCors();
Why do you need CORS? :)

2018-06-01 09:18 UTC, vaclavm commented on TodoApp/Todo.App.Services/UrlServices/UrlGenerator.cs
> +        public string GetItemUrl(Guid id, string routeName)
This method shouldn't consume routeName, rather the whole service should have some instance of provider that would provide the name. The caller of method GetItemUrl should only provide id and should not be responsible for providing the route as it gives it the knowledge of how it is created.

2018-06-01 09:18 UTC, vaclavm commented on TodoApp/TodoApp.Services.Test/IdServices/IdGeneratorTests.test.cs
> +    public class IdGeneratorTests : TestBase
It would be nice also to test guid for emptiness.

2018-06-01 09:18 UTC, vaclavm commented on TodoApp/TodoApp.Services.Test/ItemServices/ItemCacherTests.test.cs
> +    internal class ItemCacherTests : TestBase
Think about adding a test for caching - first call ItemExists and then call GetItem and test that _repository.GetAsync was called only once and not twice.

2018-06-01 09:18 UTC, vaclavm commented on TodoApp/TodoApp.Services.Test/ItemServices/ItemCreatorTests.test.cs
> +            Assert.That(result, Is.EqualTo(true)).AndThat(validItem.Id, Is.EqualTo(FakeItem.Id));
You should test that whole item is set correctly (not only Id).
Maybe you are asking: "how can I test DateTime.Now?", well you can't and therefore you should create DateTimeService and will give you data and you can mock it in tests ;-).

2018-06-01 09:18 UTC, vaclavm commented on TodoApp/TodoApp.Services.Test/ItemServices/ItemValidatorTests.test.cs
> +        public void IsValidForCreting_ItemIsValidOnlyForUpdating_FalseReturned()
Describe the name more appropriate, to better understand the result of the test - IsValidForCreting_ItemHasGuid_FalseReturned(). Please look at all other tests ;-)

2018-06-01 09:18 UTC, vaclavm commented on TodoApp/TodoApp.Services.Test/UrlServices/UrlGeneratorTests.test.cs
> +            var id = Guid.Parse("5f6a2723-040a-4398-8b63-9d55153378ba");
The GUID string can be a private variable outside this method as you use it also in the ContainsCorrectId.

2018-06-01 09:18 UTC, vaclavm commented on TodoApp/TodoApp.Services.Test/UrlServices/UrlGeneratorTests.test.cs
> +            var requestedUrl = "api/5f6a2723-040a-4398-8b63-9d55153378ba/v2.1/itemlist";
You can have it as a conts in this test, constructed from guid variable.

2018-06-07 13:47 UTC, PetrSvirak commented on TodoApp/src/TodoApp.Contract/Repositories/IItemRepository.cs
> +        Task<List<Item>> GetAllAsync();
Let's get back to `IEnumerable<Item>` here (see [this comment](https://github.com/LindaLangerova/kentico-onboarding-cs/pull/3#discussion-diff-191806205R10)) 😉

2018-06-26 12:22 UTC, vaclavm commented
Some small changes remains :)
- Services in TodoApp.Services should be internal, you can still use them in tests by providing assembly: InternalsVisibleTo into AssemblyInfo.cs
- `public async Task<Item> GetItem(Guid id)
            => _actualItem?.Id == id ? _actualItem : await _repository.GetAsync(id);`
- The naming in TodoApp.Services is good. Move contracts to proper folders and create folders for tests so TodoApp.Contracts and TodoApp.Services.Test will correspond with the Services project (see image)
- TodoApp.Services.Test -> TodoApp.Services.Tests

![image](https://user-images.githubusercontent.com/16819859/41910872-412b4504-794b-11e8-8d9d-d5783bcc11e9.png)

2018-06-26 12:23 UTC, vaclavm requested changes
Some small changes remain :)
- Services in TodoApp.Services should be internal, you can still use them in tests by providing assembly: InternalsVisibleTo into AssemblyInfo.cs
- `public async Task<Item> GetItem(Guid id)
            => _actualItem?.Id == id ? _actualItem : await _repository.GetAsync(id);`
- The naming in TodoApp.Services is good. Move contracts to proper folders and create folders for tests so TodoApp.Contracts and TodoApp.Services.Test will correspond with the Services project (see image)
- TodoApp.Services.Test -> TodoApp.Services.Tests

![image](https://user-images.githubusercontent.com/16819859/41910872-412b4504-794b-11e8-8d9d-d5783bcc11e9.png)

2018-07-02 09:39 UTC, vaclavm approved these changes
Nice work 👍 

(please review your references in task 4, there are some unused)

2018-07-02 09:40 UTC, merged